language: go

os:
  - linux

go:
  - "1.10.x"

sudo: required

services:
  - docker

env:
  - VERSION=1.52

before_deploy:
  - git config --local user.name "hunterlong"
  - git config --local user.email "info@socialeck.com"
  - git tag "v$VERSION" --force
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - "build/tokenbalance-osx-x64.tar.gz"
    - "build/tokenbalance-osx-x32.tar.gz"
    - "build/tokenbalance-linux-x64.tar.gz"
    - "build/tokenbalance-linux-x32.tar.gz"
    - "build/tokenbalance-linux-arm7.tar.gz"
    - "build/tokenbalance-linux-arm64.tar.gz"
    - "build/tokenbalance-linux-alpine.tar.gz"
    - "build/tokenbalance-windows-x64.zip"
    - "build/tokenbalance-windows-x32.zip"
  skip_cleanup: true

before_install:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then travis_wait 30 docker pull karalabe/xgo-latest; fi

before_script:
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/rendon/testcli
  - go get github.com/karalabe/xgo

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then travis_wait 30 docker pull karalabe/xgo-latest; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then /bin/bash -c .travis/build.sh; fi

script:
  - go get -u
  - go test -v
